boid_number: 100
x_pos_min: -450
x_pos_max: 50
y_pos_min: 300.0
y_pos_max: 600.0
x_vel_min: 0.0
x_vel_max: 20.0
y_vel_min: -20.0
y_vel_max: 20.0

xlim_min: -500
xlim_max: 1500
ylim_min: -500
ylim_max: 1500
frames: 50
interval: 50
